### ISSUE TITLE
This crashes on my version of PyCharm

### ISSUE THREAD

**Issue by cgeorgelee** [binh-vu/yapf-pycharm#5]
This crashes on my version of PyCharm. Not sure if this is useful to you but...

OS X 10.12.4 (16E195)
Pycharm 2017.3.4

```
[B@7091720d
java.lang.Throwable: [B@7091720d
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:139)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:106)
	at ReformatCode.reformatFile(ReformatCode.java:50)
	at ReformatCode.actionPerformed(ReformatCode.java:93)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:576)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:624)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.f(IdeKeyEventDispatcher.java:479)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:622)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by LexiconCode** [comment]
Same. By chance are you utilizing Windows Subsystem for Linux?

**Comment by mgeens** [comment]
Same issue on Ubuntu 17.10, PyCharm 2017.3.4.

**Comment by siyuany** [comment]
Same issue.

**Comment by binh-vu** [comment]
Have you tried to invoke yapf command manually on the file? 
```/usr/local/bin/yapf <file>```

This error is raised if you cannot invoke yapf command.

**Comment by LexiconCode** [comment]
`C:\Python27\Scripts\yapf.exe` ` sample.py`
and
`yapf.exe ` ` sample.py`
invoke the yapf command on windows 10
